project:
  type: website

website:
  title: "aton"
  navbar:
    left:
      - href: index.qmd
        text: Forcats

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



