project:
  type: website

website:
  title: "aton"
  navbar:
    left:
      - href: /tabs/nowcast/index.qmd
        text: Nowcast
      - href: /tabs/forcast/index.qmd
        text: Forcast


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



