project:
  type: website

website:
  title: "aton"
  navbar:
    background: "#004080"
    left:
      - href: index.qmd
        text: Home
      - href: nowcast.qmd
        text: Nowcast
      - href: forecast.qmd
        text: Forecast
    right:
      - icon: github
        href: https://github.com/benjaminhlina/aton


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



