---
title: "Home"
---
Last Updated: 
```{r, echo = FALSE}
Sys.time()
```

# Welcome

This site is designed to provide quick updates on current water temperatures of Lake Ontario and projected water temperatures based on  [NOAA's GLERL website](https://www.glerl.noaa.gov/res/glcfs/ncast.php?lake=ont) to facilitate projects on the lake. 

This site will update every 12 hours to give the next forecast and predictions. 

# Current Conditions 

- Current conditions for the array near Port Credit can be obtained at [Ajax ECCC bouy](https://weather.gc.ca/marine/weatherConditions-currentConditions_e.html?mapID=11&siteID=08203&stationID=45159).  

- Current conditions for the array near Hamilton can be obtained at [Grimbsy ECCC bouy](https://weather.gc.ca/marine/weatherConditions-currentConditions_e.html?mapID=11&siteID=08203&stationID=45139). 

- Current conditions for the array near Niagara can be obtained at [Niagara on the lake ECCC Bouy](https://seagull.glos.org/data-console/299/parameter/5265).

# Projected Conditions 

This site is designed to provide quick updates on  water temperatures 
from [NOAA's GLERL website](https://www.glerl.noaa.gov/res/glcfs/ncast.php?lake=ont) for specific areas of Lake Ontario. Please click either [Nowcast](https://benjaminhlina.github.io/aton/nowcast.html) to see current projections for the past 12 hours and [Forecast](https://benjaminhlina.github.io/aton/forecast.html) for the to next 72 hours. 
